Project_Dict = {
    "RTL8723A"  : {"ID" : 0,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8723B"  : {"ID" : 1,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # include rle0523
    "RTL8821A"  : {"ID" : 2,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RLE8761A"  : {"ID" : 3,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # include rle0557
    "RTL8703A"  : {"ID" : 4,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8763A"  : {"ID" : 5,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8703B"  : {"ID" : 6,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8723C"  : {"ID" : 7,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8822B"  : {"ID" : 8,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8723D"  : {"ID" : 9,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8821C"  : {"ID" : 10,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8763B"  : {"ID" : 11,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bbpro
    "RTL8762C"  : {"ID" : 12,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bee2
    "RTL8822C"  : {"ID" : 13,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8761B"  : {"ID" : 14,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "AMEBAD"    : {"ID" : 15,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "AMEBAZII"  : {"ID" : 16,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "NBIOT"     : {"ID" : 17,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8852A"  : {"ID" : 18,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8723F"  : {"ID" : 19,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8852B"  : {"ID" : 20,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8763C"  : {"ID" : 21,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bbpro2
    "RTL8773B"  : {"ID" : 22,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bblite
    "RTL8762A"  : {"ID" : 23,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bee
    "RTL8762B"  : {"ID" : 24,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8852C"  : {"ID" : 25,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0x80110b20,
                   "B_CUT_PATCH_ADDR": 0x80110b30},
    "RTL8763D"  : {"ID" : 26,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bbpro3
    "RTL8763E"  : {"ID" : 27,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bb2
    "RTL8753C"  : {"ID" : 28,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bblite2
    "AMEBAPRO2" : {"ID" : 29,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # AmebaPro2
    "AMEBAD2"   : {"ID" : 30,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0x80110b20,
                   "B_CUT_PATCH_ADDR": 0}, # AmebaD2
    "RTL8762E"  : {"ID" : 31,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bee3
    "RTL8762D"  : {"ID" : 32,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # sbee2
    "RTL8822E"  : {"ID" : 33,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0X802235d0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8852BP" : {"ID" : 34,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # rom code會回8852B的ID，僅新增for淼哥driver使用
    "RTL8851A"  : {"ID" : 35,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # rom code會回8852B的ID，僅新增for淼哥driver使用
    "RTL8851B"  : {"ID" : 36,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8772F"  : {"ID" : 37,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bee3pro
    "RLE1115"   : {"ID" : 38, 
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},# rle1115
    "AMEBALITE" : {"ID" : 39,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0x80110b30,
                   "B_CUT_PATCH_ADDR": 0x80110b30}, # AmebaLite
    "AMEBASMART": {"ID" : 40,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0x80110b30,
                   "B_CUT_PATCH_ADDR": 0x80110b30}, # AmebaSmart
    "RTL8762G"  : {"ID" : 41,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bee4
    "RTL8852D"  : {"ID" : 42,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "AMEBADP"   : {"ID" : 43,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # AmebaDP
    "RTL8922A"  : {"ID" : 44,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8764S"  : {"ID" : 45,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # rhino
    "RTL876XX"  : {"ID" : 46,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bee3plus
    "RTL8852BT" : {"ID" : 47,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8952A"  : {"ID" : 48,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8773E"  : {"ID" : 49,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bb2plus
    "AMEBALITE2": {"ID" : 50,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8761C_BB2" : {"ID" : 51,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8922B"  : {"ID" : 52,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
    "RTL8842A"  : {"ID" : 53,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # rom code會回8852C的ID，僅新增for淼哥driver使用
    "BB2Ultra"  : {"ID" : 54,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0}, # bb2ultra
    "RTL8922D"  : {"ID" : 55,
                   "TEST_CUT_PATCH_ADDR": 0,
                   "A_CUT_PATCH_ADDR": 0,
                   "B_CUT_PATCH_ADDR": 0},
}