ProjectInfo_Dict = {
    "RTL8723A"  : {"ID" : 0,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8723B"  : {"ID" : 1,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # include rle0523
    "RTL8821A"  : {"ID" : 2,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RLE8761A"  : {"ID" : 3,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # include rle0557
    "RTL8703A"  : {"ID" : 4,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8763A"  : {"ID" : 5,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8703B"  : {"ID" : 6,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8723C"  : {"ID" : 7,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8822B"  : {"ID" : 8,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8723D"  : {"ID" : 9,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8821C"  : {"ID" : 10,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8763B"  : {"ID" : 11,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bbpro
    "RTL8762C"  : {"ID" : 12,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bee2
    "RTL8822C"  : {"ID" : 13,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8761B"  : {"ID" : 14,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "AMEBAD"    : {"ID" : 15,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "AMEBAZII"  : {"ID" : 16,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "NBIOT"     : {"ID" : 17,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8852A"  : {"ID" : 18,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   3: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   4: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0x801200cc,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8723F"  : {"ID" : 19,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8852B"  : {"ID" : 20,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8763C"  : {"ID" : 21,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bbpro2
    "RTL8773B"  : {"ID" : 22,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bblite
    "RTL8762A"  : {"ID" : 23,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bee
    "RTL8762B"  : {"ID" : 24,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8852C"  : {"ID" : 25,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0x80110b20,
                       "Addr_PatchStartAddress" : 0x8014007c,
                       "Addr_SecurityHeaderBufferRemainSize" : 0x8014054c,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0x80110b30,
                       "Addr_PatchStartAddress" : 0x80140090,
                       "Addr_SecurityHeaderBufferRemainSize" : 0x801405a0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8763D"  : {"ID" : 26,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bbpro3
    "RTL8763E"  : {"ID" : 27,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bb2
    "RTL8753C"  : {"ID" : 28,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bblite2
    "AMEBAPRO2" : {"ID" : 29,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0x801070a0,
                       "Addr_PatchStartAddress" : 0x80120048,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # AmebaPro2
    "AMEBAD2"   : {"ID" : 30,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0x80110b20,
                       "Addr_PatchStartAddress" : 0x8014007c,
                       "Addr_SecurityHeaderBufferRemainSize" : 0x80140544,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # AmebaD2
    "RTL8762E"   : {"ID" : 31,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bee3
    "RTL8762D"  : {"ID" : 32,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # sbee2
    "RTL8822E"  : {"ID" : 33,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0x802235d0,
                       "Addr_PatchStartAddress" : 0x8028042c,
                       "Addr_SecurityHeaderBufferRemainSize" : 0x80280964,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8852BP" : {"ID" : 34,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # rom code會回8852B的ID，僅新增for淼哥driver使用
    "RTL8851A"  : {"ID" : 35,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # rom code會回8852B的ID，僅新增for淼哥driver使用
    "RTL8851B"  : {"ID" : 36,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8772F"  : {"ID" : 37,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bee3pro
    "RLE1115"   : {"ID" : 38, 
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},# rle1115
    "AMEBALITE" : {"ID" : 39,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0x80110b30,
                       "Addr_PatchStartAddress" : 0x80140090,
                       "Addr_SecurityHeaderBufferRemainSize" : 0x801405a4,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0x80110b30,
                       "Addr_PatchStartAddress" : 0x80140090,
                       "Addr_SecurityHeaderBufferRemainSize" : 0x801405a8,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # AmebaLite
    "AMEBASMART": {"ID" : 40,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0x80110b30,
                       "Addr_PatchStartAddress" : 0x80140090,
                       "Addr_SecurityHeaderBufferRemainSize" : 0x801405a4,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0x80110b30,
                       "Addr_PatchStartAddress" : 0x80140090,
                       "Addr_SecurityHeaderBufferRemainSize" : 0x801405a4,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # AmebaSmart
    "RTL8762G"  : {"ID" : 41,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bee4
    "RTL8852D"  : {"ID" : 42,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "AMEBADP"   : {"ID" : 43,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # AmebaDP
    "RTL8922A"  : {"ID" : 44,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0x80280114,
                       "Addr_SecurityHeaderBufferRemainSize" : 0x802807c0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8764S"  : {"ID" : 45,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # rhino
    "RTL876XX"  : {"ID" : 46,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bee3plus
    "RTL8852BT" : {"ID" : 47,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8952A"  : {"ID" : 48,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8773E"  : {"ID" : 49,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bb2plus
    "AMEBALITE2": {"ID" : 50,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8761C_BB2" : {"ID" : 51,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8922B"  : {"ID" : 52,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
    "RTL8842A"  : {"ID" : 53,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # rom code會回8852C的ID，僅新增for淼哥driver使用
    "BB2Ultra"  : {"ID" : 54,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}}, # bb2ultra
    "RTL8922D"  : {"ID" : 55,
                   0: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   1: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0},
                   2: {"PatchStartAddress" : 0,
                       "Addr_PatchStartAddress" : 0,
                       "Addr_SecurityHeaderBufferRemainSize" : 0,
                       "Val_SecurityHeaderBufferRemainSize" : 0}},
}